<?php
  $news = array(
  array('img'=>'img/example.png', 'title'=>'Bacon ipsum', 'text' =>'Spicy jalapeno bacon ipsum dolor amet fugiat sausage commodo cupidatat aliquip. Brisket biltong capicola boudin tri-tip swine chicken. Landjaeger laborum est sint filet mignon jowl ut dolore voluptate biltong ex drumstick. Sausage venison ullamco enim. Capicola pork loin tongue, ut drumstick venison ham hock esse jowl ea burgdoggen.' ),
  array('img'=>'img/example.png', 'title'=>'Zombie ipsum', 'text' =>'Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium. Qui animated corpse, cricket bat max brucks terribilem incessu zomby. The voodoo sacerdos flesh eater, suscitat mortuos comedere carnem virus. Zonbi tattered for solum oculi eorum defunctis go lum cerebro. Nescio brains an Undead zombies. Sicut malus putrid voodoo horror. Nigh tofth eliv ingdead.'),
  array('img'=>'img/example.png', 'title'=>'Lorem ipsum', 'text' =>'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
  array('img'=>'img/example.png', 'title'=>'The Back To The Future Lorem Ipsum', 'text' =>'I have to tell you about the future. this has gotta be a dream. Oh, then I wanna give her a call, I dont want her to worry about you. Say that again. Wait a minute, Doc. What are you talking about? What happens to us in the future? What do we become assholes or something? Nothing is coming to my mind. It was meant to be. Anyway, if Grandpa had not hit him, then none of you would have been born. You know, Doc, you left your equipment on all week. Whoa, whoa, Biff, what is that? Of course I do. Just a second, lets see if I could find it. '),
  array('img'=>'img/example.png', 'title'=>'Cupcake ipsum', 'text' =>'Cupcake ipsum dolor sit amet carrot cake marshmallow. Ice cream sweet roll tart sweet roll sweet chocolate bar croissant gummies. Jelly-o halvah biscuit jelly beans jelly beans sugar plum. Cake sugar plum apple pie marzipan donut. Cupcake pastry carrot cake cake liquorice chocolate bar bonbon. Toffee macaroon soufflé carrot cake cake marzipan icing.'),
  array('img'=>'img/example.png', 'title'=>'Space ipsum', 'text' =>"That's one small step for [a] man, one giant leap for mankind. We want to explore. We’re curious people. Look back over history, people have put their lives at stake to go out and explore … We believe in what we’re doing. Now it’s time to go."),
);

?>
